// Generated by gencpp from file misc/floatarray.msg
// DO NOT EDIT!


#ifndef MISC_MESSAGE_FLOATARRAY_H
#define MISC_MESSAGE_FLOATARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace misc
{
template <class ContainerAllocator>
struct floatarray_
{
  typedef floatarray_<ContainerAllocator> Type;

  floatarray_()
    : data()  {
    }
  floatarray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::misc::floatarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::misc::floatarray_<ContainerAllocator> const> ConstPtr;

}; // struct floatarray_

typedef ::misc::floatarray_<std::allocator<void> > floatarray;

typedef boost::shared_ptr< ::misc::floatarray > floatarrayPtr;
typedef boost::shared_ptr< ::misc::floatarray const> floatarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::misc::floatarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::misc::floatarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::misc::floatarray_<ContainerAllocator1> & lhs, const ::misc::floatarray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::misc::floatarray_<ContainerAllocator1> & lhs, const ::misc::floatarray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace misc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::misc::floatarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::misc::floatarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::misc::floatarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::misc::floatarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::misc::floatarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::misc::floatarray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::misc::floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::misc::floatarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::misc::floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "misc/floatarray";
  }

  static const char* value(const ::misc::floatarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::misc::floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::misc::floatarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::misc::floatarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct floatarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::misc::floatarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::misc::floatarray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISC_MESSAGE_FLOATARRAY_H
